name: Playwright Tests
on: [ push ]

jobs:
  playwright_github_action_demo:
    name: Playwright tests demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress
      - name: Install Playwright
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI - Dexec.args="install --with-deps"
      - name: Run tests
        run: mvn test
