name: Playwright Tests
on: [push]

jobs:
  playwright_github_action_demo:
    name: Playwright tests demo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '19'
        headless: true
    - name: Build & Install
      run: mvn -B install -D skipTests --no-transfer-progress
    - name: Install Playwright
      run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
    - run: npm install -D @playwright/test
    - name: Run tests
      run: mvn test

